version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-customers-serverless-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bj1yglddqpax"
s3_prefix = "stack-customers-serverless-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
